### ISSUE TITLE
linkedin  has blocked by cors

### ISSUE THREAD

**Issue by jeffersribeiro** [ozluy/react-social-login#8]
Error message return localhost/:1 Access to fetch at 'https://cors.bridged.cc/https://www.linkedin.com/oauth/v2/accessToken' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ozluy** [comment]
This is an old docs please check latest docs on https://developer.linkedin.com/
